import { createHmac } from "node:crypto";

const DEFAULT_MENU = ["status", "prompt", "shell", "macro", "media", "stop"];

export function buildFlashConfig({
  gatewayBaseUrl,
  deviceId,
  deviceSecret,
  environmentId = "env_replace_me",
  threadId = "thread_replace_me",
  defaultPrompt = "Continue the current task, inspect progress, and run relevant tests.",
  shellCommand = "npm test",
  wifiSsid = "your-wifi",
  wifiPassword = "your-password",
  hardwareModel = "e213-esp32-s3r8",
  firmwareVersion = "0.1.0",
  enableOtaApply = false,
  requireOtaSignature = false,
  otaManifestVerifyKey = "",
}) {
  return [
    "#pragma once",
    "",
    "// Generated by Agent Controller manufacturing tooling.",
    "// Do not commit this file. It contains device credentials.",
    "",
    `#define WIFI_SSID "${cString(wifiSsid)}"`,
    `#define WIFI_PASSWORD "${cString(wifiPassword)}"`,
    `#define GATEWAY_BASE_URL "${cString(gatewayBaseUrl)}"`,
    `#define DEVICE_ID "${cString(deviceId)}"`,
    `#define DEVICE_SECRET "${cString(deviceSecret)}"`,
    `#define ENVIRONMENT_ID "${cString(environmentId)}"`,
    `#define THREAD_ID "${cString(threadId)}"`,
    `#define DEFAULT_AGENT_PROMPT "${cString(defaultPrompt)}"`,
    `#define DEFAULT_SHELL_COMMAND "${cString(shellCommand)}"`,
    `#define HARDWARE_MODEL "${cString(hardwareModel)}"`,
    `#define FIRMWARE_VERSION "${cString(firmwareVersion)}"`,
    `#define ENABLE_OTA_APPLY ${enableOtaApply ? 1 : 0}`,
    `#define REQUIRE_OTA_SIGNATURE ${requireOtaSignature ? 1 : 0}`,
    `#define OTA_MANIFEST_VERIFY_KEY "${cString(otaManifestVerifyKey)}"`,
    "",
    "// Replace with exact board pins before production flashing.",
    "#define ENCODER_PIN_A 4",
    "#define ENCODER_PIN_B 5",
    "#define ENCODER_BUTTON_PIN 6",
    "#define EINK_CS 10",
    "#define EINK_DC 11",
    "#define EINK_RST 12",
    "#define EINK_BUSY 13",
    "#define ENABLE_EINK 1",
    "#define INSECURE_SKIP_TLS_VERIFY 1",
    "",
  ].join("\n");
}

export function buildFirmwareManifest(release, signingKey) {
  const unsigned = {
    version: release.version,
    hardwareModel: release.hardwareModel,
    url: release.url,
    sha256: release.sha256,
    sizeBytes: release.sizeBytes,
    mandatory: release.mandatory,
    releaseNotes: release.releaseNotes,
    createdAt: release.createdAt,
  };
  return {
    ...unsigned,
    signature: signManifest(unsigned, signingKey),
  };
}

export function signManifest(payload, signingKey) {
  return createHmac("sha256", signingKey)
    .update(stableJson(payload))
    .digest("hex");
}

export function isNewerVersion(candidate, current) {
  const left = parseVersion(candidate);
  const right = parseVersion(current);
  for (let index = 0; index < Math.max(left.length, right.length); index += 1) {
    const diff = (left[index] ?? 0) - (right[index] ?? 0);
    if (diff > 0) return true;
    if (diff < 0) return false;
  }
  return false;
}

export function normalizeFirmwareRelease(input) {
  return {
    version: nonEmpty(input.version, "version"),
    hardwareModel: nonEmpty(input.hardwareModel ?? "e213-esp32-s3r8", "hardwareModel"),
    url: nonEmpty(input.url, "url"),
    sha256: nonEmpty(input.sha256, "sha256").toLowerCase(),
    sizeBytes: Number.parseInt(String(input.sizeBytes ?? "0"), 10),
    mandatory: Boolean(input.mandatory),
    releaseNotes: typeof input.releaseNotes === "string" ? input.releaseNotes.trim() : "",
  };
}

export function defaultDeviceMenu() {
  return [...DEFAULT_MENU];
}

function nonEmpty(value, field) {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`${field} is required.`);
  }
  return value.trim();
}

function parseVersion(version) {
  return String(version)
    .replace(/^v/u, "")
    .split(".")
    .map((part) => Number.parseInt(part, 10))
    .map((part) => (Number.isFinite(part) ? part : 0));
}

function cString(value) {
  return String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("\"", "\\\"")
    .replaceAll("\n", "\\n");
}

function stableJson(value) {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`;
}
