import { createHmac } from "node:crypto";

import { encodeQr, renderQrAscii, renderQrSvg } from "./qrcode.mjs";

const DEFAULT_MENU = ["status", "prompt", "shell", "macro", "thread", "media", "stop"];
const DEFAULT_CLAIM_PATH = "/claim";
const DEFAULT_CLAIM_QR_ECC = "M";

export function buildFlashConfig({
  gatewayBaseUrl,
  deviceId,
  deviceSecret,
  environmentId = "env_replace_me",
  threadId = "thread_replace_me",
  defaultPrompt = "Continue the current task, inspect progress, and run relevant tests.",
  shellCommand = "npm test",
  hardwareModel = "e213-esp32-s3r8",
  firmwareVersion = "0.1.0",
  enableOtaApply = false,
  requireOtaSignature = false,
  otaManifestVerifyKey = "",
  gatewayTlsRootCaPem = "",
  gatewayTlsNextRootCaPem = "",
  // Bench callers may opt out explicitly. Factory/product callers inherit the fail-closed default.
  allowInsecureTls = false,
}) {
  return [
    "#pragma once",
    "",
    "// Generated by Agent Controller manufacturing tooling.",
    "// Do not commit this file. It contains device credentials.",
    "",
    "// No WIFI_SSID/WIFI_PASSWORD: the factory cannot know the customer's network, so Wi-Fi is",
    "// entered by the owner through the on-device SoftAP portal and stored in NVS.",
    `#define GATEWAY_BASE_URL "${cString(gatewayBaseUrl)}"`,
    `#define DEVICE_ID "${cString(deviceId)}"`,
    `#define DEVICE_SECRET "${cString(deviceSecret)}"`,
    `#define ENVIRONMENT_ID "${cString(environmentId)}"`,
    `#define THREAD_ID "${cString(threadId)}"`,
    `#define DEFAULT_AGENT_PROMPT "${cString(defaultPrompt)}"`,
    `#define DEFAULT_SHELL_COMMAND "${cString(shellCommand)}"`,
    `#define HARDWARE_MODEL "${cString(hardwareModel)}"`,
    `#define FIRMWARE_VERSION "${cString(firmwareVersion)}"`,
    "#ifndef ENABLE_OTA_APPLY",
    `#define ENABLE_OTA_APPLY ${enableOtaApply ? 1 : 0}`,
    "#endif",
    "#ifndef REQUIRE_OTA_SIGNATURE",
    `#define REQUIRE_OTA_SIGNATURE ${requireOtaSignature ? 1 : 0}`,
    "#endif",
    "#ifndef OTA_MANIFEST_VERIFY_KEY",
    `#define OTA_MANIFEST_VERIFY_KEY "${cString(otaManifestVerifyKey)}"`,
    "#endif",
    "",
    "// CrowPanel ESP32 2.13\" E-Paper HMI (122x250) pin map, from Elecrow's factory source.",
    "// Keep this block in sync with firmware/esp32-controller/include/controller_config.example.h.",
    "#define EINK_SCK 12",
    "#define EINK_MOSI 11",
    "#define EINK_RST 10",
    "#define EINK_DC 13",
    "#define EINK_CS 14",
    "#define EINK_BUSY 9",
    "#define EINK_POWER_PIN 7",
    "",
    "// Five active-low front-panel keys. This board has no quadrature encoder.",
    "#define KEY_UP_PIN 6",
    "#define KEY_DOWN_PIN 4",
    "#define KEY_OK_PIN 5",
    "#define KEY_MENU_PIN 2",
    "#define KEY_EXIT_PIN 1",
    "#define POWER_LED_PIN 19",
    "#define EXPANSION_IO_A 40",
    "#define EXPANSION_IO_B 41",
    "",
    "#define ENABLE_EINK 1",
    "// JD79661 controller, confirmed on hardware. Not SSD1680; GxEPD2 cannot drive it.",
    "#define EINK_PANEL_JD79661 1",
    `#define GATEWAY_TLS_ROOT_CA_PEM "${cString(gatewayTlsRootCaPem)}"`,
    `#define GATEWAY_TLS_NEXT_ROOT_CA_PEM "${cString(gatewayTlsNextRootCaPem)}"`,
    `#define INSECURE_SKIP_TLS_VERIFY ${allowInsecureTls ? 1 : 0}`,
    "",
  ].join("\n");
}

/**
 * The NVS seed a flashing station writes to a unit, in the CSV format
 * `nvs_partition_gen.py` consumes:
 *
 *   python nvs_partition_gen.py generate <this>.csv nvs.bin 0x6000
 *   esptool.py write_flash <nvs-offset> nvs.bin
 *
 * This is what lets the line flash **one** signed application image across a whole batch and vary
 * only a small data partition, instead of compiling a per-device binary.
 *
 * **The claim code belongs here.** Codes are stored hashed, so the gateway hands back the plaintext
 * exactly once — at issue, to the factory. Since `ensureUnclaimedDeviceClaimCode` refuses to reissue
 * a code that is still live, a unit that did not leave the line holding its own code can never
 * display one: it shows "No code" while the box beside it shows the real thing. Seeding it here is
 * what makes the printed label and the on-screen code agree from first boot, which is the whole
 * premise of the label pipeline. (Verified on hardware — omitting it produced exactly that split.)
 *
 * Wi-Fi is still absent, and stays absent: it belongs to the owner.
 *
 * Keys mirror DeviceStore's, and the namespace mirrors its `agentctl`. NVS keys are capped at 15
 * characters, which is why they are abbreviated.
 */
export function buildNvsSeedCsv({
  deviceId,
  deviceSecret,
  gatewayBaseUrl,
  claimCode,
  claimCodeExpiresAt,
  hardwareModel,
}) {
  if (!deviceId || !deviceSecret) {
    throw new Error("buildNvsSeedCsv requires deviceId and deviceSecret.");
  }
  const rows = [
    "key,type,encoding,value",
    "agentctl,namespace,,",
    `dev_id,data,string,${csvValue(deviceId)}`,
    `dev_secret,data,string,${csvValue(deviceSecret)}`,
  ];
  if (gatewayBaseUrl) rows.push(`gw_url,data,string,${csvValue(gatewayBaseUrl)}`);
  // NVS keys are capped at 15 characters, hence hw_model. Seeding it means a unit reports the board
  // it actually is rather than whatever the image it happens to be running was compiled for — which
  // is the difference between a mis-flashed unit that says so and one that lies.
  if (hardwareModel) rows.push(`hw_model,data,string,${csvValue(hardwareModel)}`);
  if (claimCode) {
    rows.push(`claim_code,data,string,${csvValue(claimCode)}`);
    if (claimCodeExpiresAt) rows.push(`claim_exp,data,string,${csvValue(claimCodeExpiresAt)}`);
  }
  return `${rows.join("\n")}\n`;
}

function csvValue(value) {
  const text = String(value);
  // A device secret is base64url and a gateway URL has no commas, but neither is worth trusting
  // blind: a malformed row silently produces a device that cannot authenticate.
  if (/[",\n]/u.test(text)) return `"${text.replaceAll('"', '""')}"`;
  return text;
}

/**
 * The URL a factory-printed QR code points at: the gateway claim page carrying
 * the device id and its single-use claim code.
 */
export function buildDeviceClaimUrl({ gatewayBaseUrl, deviceId, claimCode, claimPath = DEFAULT_CLAIM_PATH }) {
  const base = nonEmpty(gatewayBaseUrl, "gatewayBaseUrl").replace(/\/+$/u, "");
  const path = nonEmpty(claimPath, "claimPath");
  const url = new URL(`${base}${path.startsWith("/") ? path : `/${path}`}`);
  url.searchParams.set("device", normalizeDeviceId(deviceId));
  url.searchParams.set("code", normalizeClaimCode(claimCode));
  return url.toString();
}

/** Everything a printed label or a claim API response needs about one device. */
export function buildDeviceClaimPayload({ gatewayBaseUrl, deviceId, claimCode, label = "", claimPath = DEFAULT_CLAIM_PATH }) {
  const normalizedDeviceId = normalizeDeviceId(deviceId);
  const normalizedClaimCode = normalizeClaimCode(claimCode);
  return {
    deviceId: normalizedDeviceId,
    claimCode: normalizedClaimCode,
    label: typeof label === "string" ? label.trim() : "",
    claimUrl: buildDeviceClaimUrl({
      gatewayBaseUrl,
      deviceId: normalizedDeviceId,
      claimCode: normalizedClaimCode,
      claimPath,
    }),
  };
}

/** SVG QR code for a provisioned device, ready to print or serve. */
export function buildDeviceClaimQrSvg(input, options = {}) {
  const payload = buildDeviceClaimPayload(input);
  return renderQrSvg(encodeQr(payload.claimUrl, { ecc: options.ecc ?? DEFAULT_CLAIM_QR_ECC }), {
    scale: options.scale ?? 6,
    border: options.border ?? 4,
    title: options.title ?? `Claim ${payload.deviceId}`,
    xmlDeclaration: options.xmlDeclaration,
  });
}

/** Same payload rendered for a factory operator's terminal. */
export function buildDeviceClaimQrAscii(input, options = {}) {
  const payload = buildDeviceClaimPayload(input);
  return renderQrAscii(encodeQr(payload.claimUrl, { ecc: options.ecc ?? DEFAULT_CLAIM_QR_ECC }), {
    style: options.style ?? "half",
    border: options.border ?? 4,
    ansi: options.ansi === true,
  });
}

/**
 * Printable device label: QR code plus the human-readable identifiers an
 * operator needs when the camera fails them.
 */
export function buildDeviceLabelSvg(input, options = {}) {
  const payload = buildDeviceClaimPayload(input);
  const qr = encodeQr(payload.claimUrl, { ecc: options.ecc ?? DEFAULT_CLAIM_QR_ECC });
  const scale = options.scale ?? 4;
  const border = 4;
  const qrSize = (qr.size + border * 2) * scale;
  const textX = qrSize + 24;
  const width = options.width ?? Math.max(560, textX + 300);
  const height = Math.max(qrSize, 160);
  const inner = renderQrSvg(qr, { scale, border, xmlDeclaration: false })
    .split("\n")
    .filter((line) => line.startsWith("<rect") || line.startsWith("<path"))
    .join("");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="${width}" height="${height}" `
      + `viewBox="0 0 ${width} ${height}" shape-rendering="crispEdges" role="img">`,
    `<title>${escapeXml(`Agent Controller ${payload.deviceId}`)}</title>`,
    `<rect width="${width}" height="${height}" fill="#ffffff"/>`,
    `<g transform="translate(0 ${Math.round((height - qrSize) / 2)})">${inner}</g>`,
    `<g font-family="Helvetica,Arial,sans-serif" fill="#000000">`,
    `<text x="${textX}" y="34" font-size="18" font-weight="bold">${escapeXml(payload.label || "Agent Controller")}</text>`,
    `<text x="${textX}" y="64" font-size="13">${escapeXml(payload.deviceId)}</text>`,
    `<text x="${textX}" y="96" font-size="24" font-weight="bold" letter-spacing="2">${escapeXml(payload.claimCode)}</text>`,
    `<text x="${textX}" y="122" font-size="11">Scan to claim, or enter this code in the dashboard.</text>`,
    "</g>",
    "</svg>",
    "",
  ].join("\n");
}

/** Stable filename for the printed label of a device, next to its flash config. */
export function claimLabelFilename(deviceId) {
  return `${normalizeDeviceId(deviceId)}.claim-label.svg`;
}

export function buildFirmwareManifest(release, signingKey) {
  const unsigned = {
    version: release.version,
    channel: release.channel ?? "stable",
    hardwareModel: release.hardwareModel,
    url: release.url,
    sha256: release.sha256,
    sizeBytes: release.sizeBytes,
    mandatory: release.mandatory,
    releaseNotes: release.releaseNotes,
    createdAt: release.createdAt,
  };
  return {
    ...unsigned,
    signature: signManifest(unsigned, signingKey),
  };
}

export function signManifest(payload, signingKey) {
  return createHmac("sha256", signingKey)
    .update(stableJson(payload))
    .digest("hex");
}

export function isNewerVersion(candidate, current) {
  const left = parseVersion(candidate);
  const right = parseVersion(current);
  for (let index = 0; index < Math.max(left.length, right.length); index += 1) {
    const diff = (left[index] ?? 0) - (right[index] ?? 0);
    if (diff > 0) return true;
    if (diff < 0) return false;
  }
  return false;
}

export function normalizeFirmwareRelease(input) {
  const channel = typeof input.channel === "string" ? input.channel.trim().toLowerCase() : "stable";
  if (!["stable", "beta"].includes(channel)) throw new Error("channel must be stable or beta.");
  return {
    version: nonEmpty(input.version, "version"),
    channel,
    hardwareModel: nonEmpty(input.hardwareModel ?? "e213-esp32-s3r8", "hardwareModel"),
    url: nonEmpty(input.url, "url"),
    sha256: nonEmpty(input.sha256, "sha256").toLowerCase(),
    sizeBytes: Number.parseInt(String(input.sizeBytes ?? "0"), 10),
    mandatory: Boolean(input.mandatory),
    releaseNotes: typeof input.releaseNotes === "string" ? input.releaseNotes.trim() : "",
  };
}

export function defaultDeviceMenu() {
  return [...DEFAULT_MENU];
}

function normalizeDeviceId(deviceId) {
  const value = nonEmpty(deviceId, "deviceId");
  if (!/^[A-Za-z0-9_-]+$/u.test(value)) throw new Error("deviceId contains unsupported characters.");
  return value;
}

function normalizeClaimCode(claimCode) {
  const value = nonEmpty(claimCode, "claimCode").toUpperCase();
  if (!/^[A-Z0-9-]+$/u.test(value)) throw new Error("claimCode contains unsupported characters.");
  return value;
}

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;")
    .replaceAll("'", "&apos;");
}

function nonEmpty(value, field) {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`${field} is required.`);
  }
  return value.trim();
}

function parseVersion(version) {
  return String(version)
    .replace(/^v/u, "")
    .split(".")
    .map((part) => Number.parseInt(part, 10))
    .map((part) => (Number.isFinite(part) ? part : 0));
}

function cString(value) {
  return String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("\"", "\\\"")
    .replaceAll("\n", "\\n");
}

function stableJson(value) {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`;
}
